set(SRC_FILES
        App.cpp
        main.cpp
        Game/AppStart.cpp
        Game/AppLevelSelect.cpp
        Game/AppGamePlay.cpp
        Game/AppGameWin.cpp
        Game/AppGameOver.cpp
        Game/AppReset.cpp
        Game/LoadLevel.cpp
        Character/Character.cpp
        Character/Fireboy.cpp
        Character/Watergirl.cpp
        Object/GridSystem.cpp
        Mechanism/LiquidTrap.cpp
        Mechanism/Gem.cpp
        Mechanism/Gate.cpp
        Mechanism/Button.cpp
)

set(INCLUDE_FILES
        App.hpp
        Object/BackgroundImage.hpp
        Object/Option.hpp
        Character/Character.hpp
        Character/Fireboy.hpp
        Character/Watergirl.hpp
        Mechanism/Door.hpp
        Object/GridSystem.hpp
        Mechanism/LiquidTrap.hpp
        Interface/ITrap.hpp
        Interface/IGem.hpp
        Interface/ITriggerable.hpp
        Mechanism/Gem.hpp
        Mechanism/Gate.hpp
        Mechanism/Button.hpp
)

set(TEST_FILES
)
