set(SRC_FILES
        App.cpp
        main.cpp
        Game/AppStart.cpp
        Game/AppLevelSelect.cpp
        Game/AppGamePlay.cpp
        Game/AppGameWin.cpp
        Game/AppGameOver.cpp
        Game/AppReset.cpp
        Character/Character.cpp
        Character/Fireboy.cpp
        Character/Watergirl.cpp
        Object/GridSystem.cpp
        Mechanism/LiquidTrap.cpp
)

set(INCLUDE_FILES
        App.hpp
        Object/BackgroundImage.hpp
        Object/Option.hpp
        Character/Character.hpp
        Character/Fireboy.hpp
        Character/Watergirl.hpp
        Object/Door.hpp
        Object/GridSystem.hpp
        Mechanism/LiquidTrap.hpp
        Interface/ITrap.hpp
)

set(TEST_FILES
)
