#include "LevelData.hpp"

const std::vector<std::vector<CellType>> level1 = {
    {CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL, CellType::WALL,
     CellType::WALL, CellType::WALL, CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::WALL},

    // 7
    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    // 8
    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    // 11
    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::FLOOR,
     CellType::FLOOR, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::FLOOR, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::FLOOR,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    // 15
    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::WALL},

    {CellType::WALL,  CellType::FLOOR, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::WALL,  CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::EMPTY, CellType::EMPTY, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::FLOOR, CellType::FLOOR, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::EMPTY,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL},

    {CellType::WALL,  CellType::EMPTY, CellType::EMPTY, CellType::EMPTY,
     CellType::EMPTY, CellType::EMPTY, CellType::EMPTY, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::EMPTY,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL},

    {CellType::WALL,  CellType::FLOOR, CellType::FLOOR, CellType::FLOOR,
     CellType::FLOOR, CellType::FLOOR, CellType::FLOOR, CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL,  CellType::WALL,
     CellType::WALL,  CellType::WALL,  CellType::WALL},
};
